Exclude tests submodules from package
heremaps/xyz-spaces-python pull request #121
Opened 2021-08-18 13:33 UTC by minff

With current setup.py, pip install would still install submodules under "tests". Added wildcard pattern to exclude it

2021-08-18 14:08 UTC, sackh commented
Thanks @minff, also you will have to remove below line https://github.com/heremaps/xyz-spaces-python/blob/b1b33b0ac55f017127d7153f4a01852a21e0648c/MANIFEST.in#L10

2021-08-18 14:13 UTC, sackh requested changes
please remove below line as well.
https://github.com/heremaps/xyz-spaces-python/blob/b1b33b0ac55f017127d7153f4a01852a21e0648c/MANIFEST.in#L10

2021-08-18 15:02 UTC, deeplook commented
I think that was on purpose for xyzspaces when I wrote it at the beginning, so people could also run the tests easily without the need to clone the whole repo. At least I think that was the reason. But if that's an issue with including it in the QGis-Plugin feel free to remove them...

2021-08-18 16:14 UTC, minff commented
@deeplook , it is not really an issues with the QGIS plugin, but I find it strange when there is a tests package after pip install. If we want to include tests with the published package we could include it as submodule xyzspaces.tests imo.

2021-08-20 06:31 UTC, sackh approved these changes

2021-08-20 06:32 UTC, merged